on:
  push:
    branches:
      - main

name: release-please

jobs:
  release-please:
    if: github.repository_owner == 'bihealth'
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      release_name: ${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}.${{ steps.release.outputs.patch }}
      tag_name_no_v: ${{ steps.release.outputs.tag_name_no_v }}
    steps:

      - name: Create GitHub release
        uses: GoogleCloudPlatform/release-please-action@v3
        id: release
        with:
          release-type: python
          package-name: varfish-cli-ng
          token: ${{ secrets.BOT_TOKEN }}

  build-publish:
    runs-on: ubuntu-latest
    needs: release-please
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4
        if: ${{ needs.release-please.outputs.release_created }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        if: ${{ needs.release-please.outputs.release_created }}
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker prerelease image
        if: ${{ needs.release-please.outputs.release_created && github.event.release.prerelease }}
        uses: docker/build-push-action@v3
        with:
          context: docker
          push: true
          # NB: no "latest" tag in contrast to true release
          tags: "ghcr.io/bihealth/varfish-cli-ng:${{ needs.release-please.outputs.tag_name_no_v }}"

      - name: Build and push Docker release image
        if: ${{ needs.release-please.outputs.release_created && !github.event.release.prerelease }}
        uses: docker/build-push-action@v3
        with:
          context: docker
          push: true
          tags: "ghcr.io/bihealth/varfish-cli-ng:latest,ghcr.io/bihealth/varfish-cli-ng:${{ needs.release-please.outputs.tag_name_no_v }}"
